from soap_util import soap_error_action_missing, InvalidReceiptNumber
from errors_utils import Error, Observation, errors_serialize, InvalidRequest
from FECAEASolicitar import FECAEASolicitar
from FECAEAConsultar import FECAEAConsultar
from FECAEARegInformativo import FECAEARegInformativo
from FECAEASinMovimientoInformar import FECAEASinMovimientoInformar
from FECAESolicitar import FECAESolicitar
from FECompUltimoAutorizado import FECompUltimoAutorizado
from FECompConsultar import FECompConsultar
from FEDummy import FEDummy
