from AfipClient import *
	
afipClient = AfipClient('afip')
afipClient.fEDummy()
afipClient.fECompUltimoAutorizado()
# afipClient.fECAESolicitar()
# afipClient.fECAEASolicitar()
# afipClient.fECompConsultar()
# afipClient.fECAEAConsultar()
# afipClient.fECAEASinMovimientoInformar()
# afipClient.fECAEASinMovimientoConsultar()

# bsduAfipClient = AfipClient('bsdu')
# bsduAfipClient.fEDummy()
# bsduAfipClient.fECompUltimoAutorizado()
# bsduAfipClient.fECAESolicitar()
# bsduAfipClient.fECAEASolicitar()
# bsduAfipClient.fECompConsultar()
# bsduAfipClient.fECAEAConsultar()
# bsduAfipClient.fECAEASinMovimientoInformar()
# bsduAfipClient.fECAEASinMovimientoConsultar()

# afipClient.fECAEASolicitar()
# afipClient.fECompConsultar()
# afipClient.fECAEAConsultar()
# afipClient.fECAEASinMovimientoInformar()
# afipClient.fECAEASinMovimientoConsultar()

# afipClient.fEParamGet("FEParamGetCotizacion")
# afipClient.fEParamGet("FEParamGetPtosVenta")
# afipClient.fEParamGet("FEParamGetTiposCbte")
# afipClient.fEParamGet("FEParamGetTiposConcepto")
# afipClient.fEParamGet("FEParamGetTiposDoc")
# afipClient.fEParamGet("FEParamGetTiposIva")
# afipClient.fEParamGet("FEParamGetTiposMonedas")
# afipClient.fEParamGet("FEParamGetTiposOpcional")
# afipClient.fEParamGet("FEParamGetTiposPaises")
# afipClient.fEParamGet("FEParamGetTiposTributos")
# afipClient.fEParamGet("FECompTotXRequest")
