import json
import random

from base64 import b64encode, b64decode


def _random_byte_array(n):
    """Returns a byte array with `n` random bytes."""

    return bytearray(random.getrandbits(8) for _ in range(n))


def build_token(tributary_id):
    """Creates an authentication token for the WSAA."""

    # uses a random buffer to make the token larger
    buf = b64encode(_random_byte_array(n=550))
    data = json.dumps({'tributary_id': tributary_id, 'dummy': buf})

    # returns the token and fake sign
    return b64encode(data), b64encode(buf)


def parse_token(token):
    """Parses a token generated by `build_token` and returns its contents."""

    data = b64decode(token)
    decoded = json.loads(data)
    return decoded['tributary_id']
